version: "3"
services:
  curso-nestjs-api-prisma:
    container_name: curso-nestjs-api-prisma
    hostname: curso-nestjs-api-prisma
    image: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ~/.docker/mysql/curso-nestjs-api-prisma/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      TZ: America/Sao_Paulo